### ISSUE TITLE
Screensaver Won't Activate when Eruption Is Running

### ISSUE THREAD

**Issue by erockce** [X3n0m0rph59/eruption-roccat-vulcan#13] opened 2020-08-09 04:34 UTC
Hi @X3n0m0rph59 

Since the new version was installed today, my screen saver is now not activating if the `eruption` service is running.

If I stop the service, the screen saver (simple blanking) works again.  I did not have this issue with prior `0.1.11` version.

When I try `xset s activate` the screen blanks for 3 seconds, but then comes back.

If the `eruption` service is not running, the screen saver will activate at the specified timeout. I have also reset all the profile slots to `default.profile` and restarted the `eruption` service multiple times but the problem still occurs.

Please let me know if you need any more information.

Eruption Version
```
$ dpkg -s eruption-roccat-vulcan-git | grep "^Version"
Version: 0.1.12-ubuntu1
```
Distribution:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

Service configuration
```
$ cat /etc/eruption/eruption.conf
# Eruption - Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards
# Main configuration file

[global]
profile_dir = "/var/lib/eruption/profiles/"
script_dir = "/usr/share/eruption/scripts/"

# select your keyboard variant
# keyboard_variant = "ANSI"
keyboard_variant = "ISO"

# Mouse handling
enable_mouse = false
grab_mouse = false

# "Away from keyboard" handling
afk_profile = "matrix.profile"
afk_timeout_secs = 300
```

Eruption state file:
```
$ cat /var/lib/eruption/eruption.state 
active_slot = 3
profiles = [
    'default.profile',
    'default.profile',
    'default.profile',
    'default.profile',
]
enable_sfx = false
brightness = 20
```

Here is my `xset` parameters
```
$ xset q
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  500    repeat rate:  20
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  0/1    threshold:  1
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  10    cycle:  60
Colors:
  default colormap:  0x22    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
DPMS (Energy Star):
  Standby: 1800    Suspend: 0    Off: 3600
  DPMS is Enabled
  Monitor is On
```

Relevant `journalctl -xe -u eruption`:
```
-- The start-up result is RESULT.
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption > Starting user-mode driver for ROCCAT Vulcan 100/12x series keyboards: Version 0.1.12
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption > Loading saved state...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  WARN  eruption::state > Brightness configuration value is set very low, the LEDs will probably stay dark!
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption        > Registering plugins...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Keyboard - Process keyboard events
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Mouse - Process mouse events
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Macros - Inject programmable keyboard and mouse events
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Introspection - Provide runtime status of the Eruption daemon
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Persistence - A storage and persistence layer for Lua Scripts
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Profiles - Switch profiles based on system state
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: System - Basic system information and status
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Sensors - Query system sensor values
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugin_manager > Registering plugin: Audio - Audio related functions
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::persistence > Loading persistent state data from disk...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Plugins loaded and initialized successfully
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Enumerating connected devices...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::hwdevices            > Found Control interface: "0002:0003:01": ROCCAT Vulcan AIMO
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::hwdevices            > Found LED interface: "0002:0003:03": ROCCAT Vulcan AIMO
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Device enumeration completed
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Spawning keyboard input thread...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Mouse support is DISABLED by configuration
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Waiting for tasks to complete...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Opening keyboard device...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::keyboard    > Now listening on: /dev/input/event3
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::keyboard    > Input device name: "ROCCAT ROCCAT Vulcan AIMO"
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::keyboard    > Input device ID: bus 0x3 vendor 0x1e7d product 0x3098
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::keyboard    > Physical location: usb-0000:00:14.0-2/input0
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption::plugins::keyboard    > Grabbing the keyboard device exclusively
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Initializing keyboard device...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Configuring keyboard LEDs...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Opening mouse device...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > This mouse is currently not supported, falling back to the generic driver
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Performing late initializations...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Initializing D-Bus API...
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Late initializations completed
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Startup completed
Aug 08 22:25:27 <hostname redacted> eruption[29602]:  INFO  eruption                       > Switching to profile: default.profile
```

**Comment by X3n0m0rph59** [comment] 2020-08-09 07:07
Hi! Thanks for your bug report!

Sounds like `eruption` somehow injects input events that prohibit the screensaver from being run.

I have tried on a Ubuntu 18.04 virtual machine as well as on my development box, but was unable to reproduce this issue.
On both machines the screensaver/blanking works as expected:
```sh
$ xset s 10
```
Wait 10 seconds...

Screen will blank, as expected after 10 seconds, and stay this way until I move the mouse or press a key.
This works with `eruption` running, as well as with `eruption.service` being masked and stopped.

```sh
$ xset s activate
```
fails to blank the screen most of the time. This one will work though:
```sh
$ sleep 1; xset s activate
```

I have tested all permutations of configuration parameters (assigned `true` or `false`, `0` or `5`):
`enable_mouse`, `grab_mouse`, `afk_timeout_secs`

To verify that spurious input events are the culprit in deed, could you please run `sudo evtest`:
```sh
$ sudo apt install evtest
$ sudo evtest
```
and select the _Eruption Virtual Keyboard/Mouse_ devices. If you see events being logged while you don't perform any input actions at all, then this will most likely be the cause of the issue.

**Comment by X3n0m0rph59** [comment] 2020-08-09 08:10
I can reproduce it now on my development box! It seems that something is resetting the screensaver timeout. So spurious input events are not the root cause of this issue.

I will investigate...

**Comment by X3n0m0rph59** [comment] 2020-08-09 11:08
I just set up an Ubuntu 18.04 VM using the xfce4 desktop environment. Furthermore, I did install the xscreensaver package and configured a timeout of 1 minute, using the screensaver configuration GUI (Xfce4 menu item: Settings / Screensaver). This way, the screensaver seems to work alright.

Could you please tell me how you set the timeout of the screensaver? Did you set it using the xscreensaver GUI or via `xset s <secs>`. The `xset s <secs>` value often gets reset for a yet to be discovered reason, on both of my test machines.

**Comment by erockce** [comment] 2020-08-09 20:37
I wasn't expecting you to already attempt (and in one case) reproduce my problem!

I'm sorry for the quick knee-jerk issue I created yesterday but it appears things with eruption might be working after all.

More in-depth investigation and monitoring is required. Today my screensaver is working as expected.  I did not change anything from yesterday.  I let my system sit idle for 5 minutes (300 seconds) then the screen blanked and Eruption AFK mode kicked into the `matrix` display as defined by the configuration.

The only item that appears to have changed is that `cycle` for screen saver is now `0` which I did not modify myself but maybe there are some defaults that get set if something is not correct.

```
$ xset q
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  500    repeat rate:  20
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  0/1    threshold:  1
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  300    cycle:  0
Colors:
  default colormap:  0x22    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
DPMS (Energy Star):
  Standby: 1800    Suspend: 0    Off: 3600
  DPMS is Enabled
  Monitor is On
```

Background on my system installation is from Xubuntu 18.04 and I use Light DM with XFCE4. As far as display and screen related packages, I do not have the `xscreensaver` package installed and instead just let "screen saving" be a simple screen blank provided by the X server (specifically is turning the HDMI signal OFF to the monitor).  I do have `light-locker` installed, a program called `caffeine` (which wasn't activated), and `redshift` and `redshift-gtk`.

Here is `evtest` for the keyboard and mouse... 

`evtest` for keyboard

```
$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Sleep Button
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	ROCCAT ROCCAT Vulcan AIMO
/dev/input/event7:	ROCCAT ROCCAT Vulcan AIMO
/dev/input/event8:	Logitech M325
/dev/input/event10:	Video Bus
/dev/input/event11:	HDA Intel HDMI HDMI/DP,pcm=3
/dev/input/event12:	HDA Intel HDMI HDMI/DP,pcm=7
/dev/input/event13:	HDA Intel HDMI HDMI/DP,pcm=8
/dev/input/event14:	HDA Intel HDMI HDMI/DP,pcm=9
/dev/input/event15:	HDA Intel HDMI HDMI/DP,pcm=10
/dev/input/event16:	HDA Intel PCH Mic
/dev/input/event17:	HDA Intel PCH Headphone
/dev/input/event18:	Eruption Virtual Keyboard
/dev/input/event19:	Eruption Virtual Mouse
Select the device event number [0-19]: 18
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x59 product 0x123 version 0x1
Input device name: "Eruption Virtual Keyboard"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 129 (KEY_AGAIN)
    Event code 130 (KEY_PROPS)
    Event code 131 (KEY_UNDO)
    Event code 132 (KEY_FRONT)
    Event code 133 (KEY_COPY)
    Event code 134 (KEY_OPEN)
    Event code 135 (KEY_PASTE)
    Event code 136 (KEY_FIND)
    Event code 137 (KEY_CUT)
    Event code 138 (KEY_HELP)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 150 (KEY_WWW)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 161 (KEY_EJECTCD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 173 (KEY_REFRESH)
    Event code 176 (KEY_EDIT)
    Event code 177 (KEY_SCROLLUP)
    Event code 178 (KEY_SCROLLDOWN)
    Event code 179 (KEY_KPLEFTPAREN)
    Event code 180 (KEY_KPRIGHTPAREN)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 186 (KEY_F16)
    Event code 187 (KEY_F17)
    Event code 188 (KEY_F18)
    Event code 189 (KEY_F19)
    Event code 190 (KEY_F20)
    Event code 191 (KEY_F21)
    Event code 192 (KEY_F22)
    Event code 193 (KEY_F23)
    Event code 194 (KEY_F24)
    Event code 240 (KEY_UNKNOWN)
    Event code 464 (KEY_FN)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1597003961.765217, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1597003961.765217, -------------- SYN_REPORT ------------
Event: time 1597004394.510928, type 1 (EV_KEY), code 57 (KEY_SPACE), value 1
Event: time 1597004394.510928, -------------- SYN_REPORT ------------
Event: time 1597004394.568759, type 1 (EV_KEY), code 57 (KEY_SPACE), value 0
Event: time 1597004394.568759, -------------- SYN_REPORT ------------
Event: time 1597004399.165890, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1597004399.165890, -------------- SYN_REPORT ------------
Event: time 1597004399.393921, type 1 (EV_KEY), code 46 (KEY_C), value 1
Event: time 1597004399.393921, -------------- SYN_REPORT ------------
```

I waited over 5 minutes letting the screen saver activate and Eruption AFK start; then cancelled with a press of the `spacebar`, then `Ctrl-C` to exit

Then ran `evtest` for the mouse

```
$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Sleep Button
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	ROCCAT ROCCAT Vulcan AIMO
/dev/input/event7:	ROCCAT ROCCAT Vulcan AIMO
/dev/input/event8:	Logitech M325
/dev/input/event10:	Video Bus
/dev/input/event11:	HDA Intel HDMI HDMI/DP,pcm=3
/dev/input/event12:	HDA Intel HDMI HDMI/DP,pcm=7
/dev/input/event13:	HDA Intel HDMI HDMI/DP,pcm=8
/dev/input/event14:	HDA Intel HDMI HDMI/DP,pcm=9
/dev/input/event15:	HDA Intel HDMI HDMI/DP,pcm=10
/dev/input/event16:	HDA Intel PCH Mic
/dev/input/event17:	HDA Intel PCH Headphone
/dev/input/event18:	Eruption Virtual Keyboard
/dev/input/event19:	Eruption Virtual Mouse
Select the device event number [0-19]: 19
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x59 product 0x124 version 0x1
Input device name: "Eruption Virtual Mouse"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 256 (BTN_0)
    Event code 257 (BTN_1)
    Event code 258 (BTN_2)
    Event code 259 (BTN_3)
    Event code 260 (BTN_4)
    Event code 261 (BTN_5)
    Event code 262 (BTN_6)
    Event code 263 (BTN_7)
    Event code 264 (BTN_8)
    Event code 265 (BTN_9)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
    Event code 277 (BTN_FORWARD)
    Event code 278 (BTN_BACK)
    Event code 279 (BTN_TASK)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 2 (REL_Z)
    Event code 6 (REL_HWHEEL)
    Event code 8 (REL_WHEEL)
    Event code 11 (?)
    Event code 12 (?)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
 ^C
```

No issues or "ghosts in the machine" detected! ;-)

Side question...although I have the mouse options set to `false`, why is there still activation of the `Eruption Virtual Mouse`?  Why would I need this if I'm relying on the mouse driver provided by the kernel?

**Comment by erockce** [comment] 2020-08-10 02:43
For what it is worth I restored all of my previous custom profiles to slots (which right now are nothing more than renamed presets (`preset-blue-red.profile`, `preset-red-yellow.profile`, `profile3.profile`, and `spectrum-analyzer.profile`) to see if there was something strange in the profiles or scripts they used to cause the reported issue.  My computer has been left on all day and the screen has blanked and Eruption goes to AFK mode after 5 minutes as expected without any issues.

Maybe another recent update or removal of an X library caused the temporary issue.  I will have to go through the apt logs for details.

At this point if you do not feel there is any issue or cannot reproduce the reported problem further, I think this issue can be closed.

**Comment by X3n0m0rph59** [comment] 2020-08-10 04:11
Hi! Thanks for the quick reply!

>I'm sorry for the quick knee-jerk issue I created yesterday but it appears things with eruption might be working after all.

Not a problem at all! Please feel free to open up issues anytime!
Your `sudo evtest` output is looking good, so we can be reasonably sure that spurious events aren't involved here.

I noticed the same during testing yesterday. The values set by `xset s <num> <num>` get magically reset.
I suspect that we aren't supposed to use the low-level configuration stuff of the X server, but instead something like `xfce4-power-manager-settings` instead.

>Side question...although I have the mouse options set to false, why is there still activation of the Eruption Virtual Mouse? Why would I need this if I'm relying on the mouse driver provided by the kernel?

I decided to not completely remove the `Eruption Virtual Mouse` device when `enable_mouse = false` and `grab_mouse = false`, so that we are still able to inject mouse events to the input system. Said virtual events just wouldn't originate from "real" mouse events anymore. The only time you would see events on the virtual mouse in that case would be, when a Lua script like `user-macros.lua` injects mouse events by calling `inject_mouse_button(button_index, down)` or `inject_mouse_wheel(direction)`, e.g. as part of a custom "Easy Shift" (keyboard) macro.

I'm closing this issue now, but please re-open it if you find that eruption is involved somehow!

**Closed by X3n0m0rph59** 2020-08-10 04:11 UTC
Labels: bug
